# Generated by Django 4.1.2 on 2022-10-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_cars_insurancecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidents',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
